import type { Job } from '../types';
import { format, subDays } from 'date-fns';

const today = new Date();

export const mockJobs: Job[] = [
  {
    id: 'job_1',
    company: 'Google',
    role: 'Senior QA Engineer',
    location: 'Remote',
    url: 'https://careers.google.com/...',
    priority: 'High',
    resumeUsed: 'SDE_Resume_v3.pdf',
    dateApplied: format(subDays(today, 2), 'yyyy-MM-dd'),
    salaryRange: '$150k - $180k',
    nextAction: 'Prep for technical screen',
    notes: 'Referred by Alex.',
    status: 'Interviewing',
    createdAt: new Date(Date.now() - 200000).toISOString(),
  },
  {
    id: 'job_2',
    company: 'Stripe',
    role: 'QA Automation Lead',
    location: 'New York, NY',
    url: 'https://stripe.com/jobs/...',
    priority: 'High',
    resumeUsed: 'QA_Lead_Resume.pdf',
    dateApplied: format(subDays(today, 5), 'yyyy-MM-dd'),
    salaryRange: '$160k - $190k',
    nextAction: 'Follow up with recruiter',
    notes: 'Applying directly on portal.',
    status: 'Applied',
    createdAt: new Date(Date.now() - 500000).toISOString(),
  },
  {
    id: 'job_3',
    company: 'Spotify',
    role: 'Test Engineer',
    location: 'Remote (EU)',
    url: 'https://spotify.com/jobs',
    priority: 'Medium',
    resumeUsed: 'General_QA.pdf',
    dateApplied: format(subDays(today, 10), 'yyyy-MM-dd'),
    salaryRange: '€80k - €100k',
    nextAction: '',
    notes: 'Love the product.',
    status: 'Wishlist',
    createdAt: new Date(Date.now() - 1000000).toISOString(),
  },
  {
    id: 'job_4',
    company: 'Netflix',
    role: 'Software Engineer in Test',
    location: 'Los Gatos, CA',
    url: 'https://jobs.netflix.com',
    priority: 'High',
    resumeUsed: 'SDET_Resume.pdf',
    dateApplied: format(subDays(today, 8), 'yyyy-MM-dd'),
    salaryRange: '$200k+',
    nextAction: 'Complete coding challenge',
    notes: 'Recruiter reached out on LinkedIn.',
    status: 'Screening',
    createdAt: new Date(Date.now() - 800000).toISOString(),
  },
  {
    id: 'job_5',
    company: 'Amazon',
    role: 'QAE II',
    location: 'Seattle, WA',
    url: 'https://amazon.jobs',
    priority: 'Medium',
    resumeUsed: 'SDE_Resume_v3.pdf',
    dateApplied: format(subDays(today, 1), 'yyyy-MM-dd'),
    salaryRange: '$130k - $160k',
    nextAction: 'Update resume for next step',
    notes: '',
    status: 'Preparing',
    createdAt: new Date(Date.now() - 100000).toISOString(),
  },
  {
    id: 'job_6',
    company: 'Meta',
    role: 'QA Engineer',
    location: 'Menlo Park, CA',
    url: 'https://metacareers.com',
    priority: 'High',
    resumeUsed: 'General_QA.pdf',
    dateApplied: format(subDays(today, 12), 'yyyy-MM-dd'),
    salaryRange: '$140k - $170k',
    nextAction: '',
    notes: 'Ghosted after HM screen?',
    status: 'Ghosted/Closed',
    createdAt: new Date(Date.now() - 1200000).toISOString(),
  },
  {
    id: 'job_7',
    company: 'Apple',
    role: 'QA Automation Engineer',
    location: 'Cupertino, CA',
    url: 'https://apple.com/jobs',
    priority: 'Medium',
    resumeUsed: 'QA_Lead_Resume.pdf',
    dateApplied: format(subDays(today, 14), 'yyyy-MM-dd'),
    salaryRange: '',
    nextAction: '',
    notes: 'Position closed internally.',
    status: 'Declined',
    createdAt: new Date(Date.now() - 1400000).toISOString(),
  },
  {
    id: 'job_8',
    company: 'Discord',
    role: 'Senior SDET',
    location: 'Remote',
    url: 'https://discord.com/jobs',
    priority: 'Low',
    resumeUsed: 'SDET_Resume.pdf',
    dateApplied: format(subDays(today, 4), 'yyyy-MM-dd'),
    salaryRange: '$160k',
    nextAction: '',
    notes: '',
    status: 'Applied',
    createdAt: new Date(Date.now() - 400000).toISOString(),
  },
  {
    id: 'job_9',
    company: 'Airbnb',
    role: 'Quality Engineer',
    location: 'Remote',
    url: 'https://careers.airbnb.com',
    priority: 'High',
    resumeUsed: 'General_QA.pdf',
    dateApplied: format(subDays(today, 7), 'yyyy-MM-dd'),
    salaryRange: '$150k',
    nextAction: 'Sign offer letter!',
    notes: 'Great team, loved the loop.',
    status: 'Offer Negotiation',
    createdAt: new Date(Date.now() - 700000).toISOString(),
  },
  {
    id: 'job_10',
    company: 'Vercel',
    role: 'Test Engineer',
    location: 'Remote',
    url: 'https://vercel.com/careers',
    priority: 'High',
    resumeUsed: 'SDET_Resume.pdf',
    dateApplied: format(subDays(today, 3), 'yyyy-MM-dd'),
    salaryRange: '$140k',
    nextAction: 'Send thank you email',
    notes: '',
    status: 'Follow-up',
    createdAt: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: 'job_11',
    company: 'Atlassian',
    role: 'QA Analyst',
    location: 'Sydney (Remote)',
    url: 'https://atlassian.com',
    priority: 'Medium',
    resumeUsed: 'General_QA.pdf',
    dateApplied: format(subDays(today, 9), 'yyyy-MM-dd'),
    salaryRange: 'A$120k',
    nextAction: '',
    notes: 'No response yet.',
    status: 'Applied',
    createdAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'job_12',
    company: 'Notion',
    role: 'QA Engineer',
    location: 'San Francisco, CA',
    url: 'https://notion.so/careers',
    priority: 'High',
    resumeUsed: 'QA_Lead_Resume.pdf',
    dateApplied: format(subDays(today, 6), 'yyyy-MM-dd'),
    salaryRange: '$155k',
    nextAction: 'Onsite interview next Monday',
    notes: 'Prepare system design for QA.',
    status: 'Interviewing',
    createdAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'job_13',
    company: 'Linear',
    role: 'Product QA',
    location: 'Remote',
    url: 'https://linear.app',
    priority: 'Low',
    resumeUsed: 'General_QA.pdf',
    dateApplied: format(subDays(today, 11), 'yyyy-MM-dd'),
    salaryRange: '',
    nextAction: '',
    notes: 'Automated rejection email.',
    status: 'Rejected',
    createdAt: new Date(Date.now() - 1100000).toISOString(),
  },
  {
    id: 'job_14',
    company: 'Github',
    role: 'Senior QA Engineer',
    location: 'Remote',
    url: 'https://github.com/careers',
    priority: 'Medium',
    resumeUsed: 'QA_Lead_Resume.pdf',
    dateApplied: format(subDays(today, 2), 'yyyy-MM-dd'),
    salaryRange: '$140k - $160k',
    nextAction: '',
    notes: 'Reviewing job description.',
    status: 'Wishlist',
    createdAt: new Date(Date.now() - 250000).toISOString(),
  },
  {
    id: 'job_15',
    company: 'Slack',
    role: 'Automation Engineer',
    location: 'Remote',
    url: 'https://slack.com',
    priority: 'Medium',
    resumeUsed: 'SDET_Resume.pdf',
    dateApplied: format(subDays(today, 0), 'yyyy-MM-dd'),
    salaryRange: '$150k',
    nextAction: 'Fixing resume format',
    notes: '',
    status: 'Preparing',
    createdAt: new Date(Date.now() - 10000).toISOString(),
  }
];
